name: CI Pipeline

on:
  push:
    branches:
      - emad
  pull_request:
    branches:
      - emad

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Specify the Node.js versions you want to test with

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm" # Enables caching for faster builds

      - name: Install dependencies
        run: npm install
        
      - name: Run linters
        run: npm run lint # if you have lint script

      - name: Build project
        run: npm run build # Assuming you have a build script in package.json

